data:
  dataset_root: "data/processed/localization"
  train_dataset: "data/processed/localization/train"
  valid_dataset: "data/processed/localization/valid"
  test_dataset: "data/processed/localization/test"
  train_ann: "data/processed/localization/train/location.csv"
  valid_ann: "data/processed/localization/valid/location.csv"
  test_ann: "data/processed/localization/test/location.csv"
  train_batch_size: 8
  valid_batch_size: 1
  test_batch_size: 1

transforms:
  train:
    - transform: "Crop"
      params:
        size: [[288, 0], [4000, 2848]]
    - transform: "Resize"
      params:
        size: [512, 512]
  valid:
    - transform: "Crop"
      params:
        size: [[288, 0], [4000, 2848]]
    - transform: "Resize"
      params:
        size: [512, 512]
  test:
    - transform: "Crop"
      params:
        size: [[288, 0], [4000, 2848]]
    - transform: "Resize"
      params:
        size: [512, 512]

device:
  name: "cuda"

model: 
  name: "VGGRegressor"

loss: 
  type: "MSE"
  params: 
    reduction: "mean"

optimizer:
  type: "Adam"
  params:
    lr: 0.001
    betas: [0.9, 0.999]

lr_scheduler:
  type: "exponential"
  params:
    gamma: 0.5

logger:
  path: "none"
