pipeline:
  device: "cuda"
  epochs: 25

data:
  train:
    path: "../data/processed/localization/train"
    annotations: "location.csv"
    batch_size: 8
  valid:
    path: "../data/processed/localization/valid"
    annotations: "location.csv"
    batch_size: 1
  test:
    path: "../data/processed/localization/test"
    annotations: "location.csv"
    batch_size: 1

transforms:
  train:
    - transform: "Crop"
      params:
        top: 288
        left: 0
        height: 2000
        width: 3200
    - transform: "Resize"
      params:
        output_size: 512
  valid:
    - transform: "Crop"
      params:
        top: 288
        left: 0
        height: 2000
        width: 3200
    - transform: "Resize"
      params:
        output_size: 512
  test:
    - transform: "Crop"
      params:
        top: 288
        left: 0
        height: 2000
        width: 3200
    - transform: "Resize"
      params:
        output_size: 512

model: 
  name: "VGGRegressor"
  params:
    in_channels: 3

loss: 
  type: "MSELoss"
  params: 
    reduction: "mean"

optimizer:
  type: "Adam"
  params:
    lr: 0.001
    betas: [0.9, 0.999]

lr_scheduler:
  type: "ExponentialLR"
  params:
    gamma: 0.5

logger:
  path: "none"
